name: Test Release

on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check gh version
        shell: pwsh
        run: gh --version

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: ../publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}