name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish DeskBurst.csproj -c Release --property:PublishDir=../publish

      - name: Create GitHub Release
        run: |
          $tag = "${{ github.ref_name }}"
          $files = Get-ChildItem -Path "../publish/*" -File | ForEach-Object { $_.FullName }
          $fileArgs = $files | ForEach-Object { "--asset=`"$_`"" }
          gh release create $tag `
            --repo="$env:GITHUB_REPOSITORY" `
            --title="$($tag -replace '^v', '')" `
            --generate-notes `
            --latest `
            $fileArgs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
